//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Employees = new HashSet<Employee>();
    }

    public int DepartmentID { get; set; }
    public string DepartmentName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees { get; set; }
}

public partial class Employee
{
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Hiredate { get; set; }
    public Nullable<decimal> Salary { get; set; }
    public int DepartmentID { get; set; }
    public string Address { get; set; }

    public virtual Department Department { get; set; }
}
